test ci-cd

diff --git a/.github/workflows/NewApp.yaml b/.github/workflows/NewApp.yaml
--- a/.github/workflows/NewApp.yaml
+++ b/.github/workflows/NewApp.yaml
@@ -106,5 +106,53 @@ jobs:
     - name: Docker Build Loadrunner
       if: ${{ env.BUILD == 'true' }}
       run: |
-        docker build . -t LR -f NewApp/ngsa-csharp/Ngsa.LodeRunner/Dockerfile
+        docker build . -t lr -f NewApp/ngsa-csharp/Ngsa.LodeRunner/Dockerfile
   
+    - name: Start data service
+      if: ${{ env.BUILD == 'true' }}
+      run: |
+        # run the app
+        docker run -d --name ds -p 4122:4122 ds --in-memory
+        
+        echo "Waiting for web server to start ..."
+        
+        wait_time=10        
+        sleep $wait_time
+
+        # wait up to 30 seconds for web server to start
+        while true
+        do
+            if curl localhost:4122/version ; then
+                echo -e "\n web server is running"
+                break
+            fi
+            if [ $wait_time -gt 30 ] ; then
+              echo -e "\n timeout waiting for web server to start"
+              exit 1
+            fi
+            
+            sleep 1
+            ((wait_time=wait_time+1))
+        done
+
+    - name: Run LodeRunner
+      if: ${{ env.BUILD == 'true' }}
+      run: |
+        # run loderunner validation test
+        # fail on any validation errors
+        docker run --name lr lr -s localhost:4122 --max-errors 1 -f baseline.json benchmark.json
+
+    - name: Display failed docker logs
+      if: ${{ failure() }}
+      run: |
+        docker logs ds
+
+    - name: Display coverage results
+      if: ${{ env.BUILD == 'true' }}
+      run: |
+        # wait for data service to shutdown
+        sleep 15
+
+        # display the results
+        docker logs ds | tail -n 15
+
